global:
  security:
    allowInsecureImages: true

postgresql:
  password: "SenhaSuperSegura123"
  repmgrPassword: "SenhaRepmgrSegura123"
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql-repmgr
    tag: 17.6.0-debian-12-r2

pgpool:
  adminPassword: "SenhaAdminPgpool123"
  image:
    registry: docker.io
    repository: bitnamilegacy/pgpool
    tag: 4.6.3-debian-12-r0

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce

replicaCount: 2
